/*CRIAÇÃO DO BANCO DE DADOS*/
CREATE DATABASE IF NOT EXISTS CADASTRO;

/*UTILIZAÇÃO DO BANCO DE DADOS*/
USE CADASTRO;

/*CASO NECESSÁRIO DELETAR ALGUMA TABELA, DESCOMENTAR A LINHA ESPERCÍFICA*/
#DROP TABLE IF EXISTS PESSOAS;

/*  CRIAÇÃO DA TABELA PESSOAS  */
CREATE TABLE IF NOT EXISTS PESSOAS(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    IDADE TINYINT(3) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    PESO FLOAT(3) NOT NULL,
    ALTURA FLOAT(3) NOT NULL,
    NACIONALIDADE VARCHAR(20) NOT NULL
);

DESCRIBE PESSOAS;   /*  MOSTRA TABELA PESSOAS DE FORMA DESCRITIVA NA ABA RESULTS    */